### ISSUE TITLE
Too many open files in system

### ISSUE THREAD

**Issue by nuin** [PapenfussLab/socrates#2]
On a busy system, the application ends in an error due too many files open. I am testing in a less busy box and see the result. The error stack is 

`````` java
Task completed ( 3827 / 4371 )
Task completed ( 3828 / 4371 )
Task completed ( 3829 / 4371 )
java.util.concurrent.ExecutionException: htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: 57375-RB_short_sc.bai (Too many open files in system)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at au.edu.wehi.socrates.RealignmentClustering.runClustering(RealignmentClustering.java:256)
    at au.edu.wehi.socrates.RealignmentClustering.clusterRealignedSC(RealignmentClustering.java:190)
    at au.edu.wehi.socrates.SOCRATES.main(SOCRATES.java:272)
Caused by: htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: 57375-RB_short_sc.bai (Too many open files in system)
    at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:171)
    at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:165)
    at htsjdk.samtools.util.Lazy.get(Lazy.java:24)
    at htsjdk.samtools.FileInputResource.asUnbufferedSeekableStream(SamInputResource.java:194)
    at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:228)
    at au.edu.wehi.socrates.RealignmentClustering$ClusteringWorker.call(RealignmentClustering.java:342)
    at au.edu.wehi.socrates.RealignmentClustering$ClusteringWorker.call(RealignmentClustering.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: 57375-RB_short_sc.bai (Too many open files in system)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
    at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:169)
    ... 10 more
Used memory is: 2036MB
Socrates has run completely.```
``````

**Comment by nuin** [comment]
Works fine in a less busy machine.

**Comment by d-cameron** [comment]
You appear to have hit your OS-level limit on open file handles.
On linux this can be increased with ulimit. Eg _ulimit -u 4096_

**Comment by nuin** [comment]
Yes, I increased the limit, but at some point Socrates had more than 500 files opened, with other processes running on the machine it failed due to this error. The issue is more of a warning to whoever might run into a similar problem in the future. My pipeline machine(s) only run a limited number of processes, so they should not have a problem, OTOH, my development box has the error.

**Comment by hdashnow** [comment]
Have there been any developments on this? I'm having the same error. My number of file handles is already set quite high: 65535

**Comment by jibsch** [comment]
That's high indeed. 
One factor that keeps the file handles down is the number of threads specified. A lower number will result in fewer handles.

**Comment by hdashnow** [comment]
I'm running it with default settings, i.e. 1 thread and 10g memory.

Also, I noticed that just before it failed it printed "Task completed ( 65675 / 176715 )". 65675 is just over my file handle limit.

**Comment by karthigayini** [comment]
Is there an update on this? I am running into the same issue. 
"Task completed ( 16431 / 5341546 )
java.io.FileNotFoundException: results_Socrates_paired_TOCL_005_realignmetBam.txt (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:263)
	at au.edu.wehi.socrates.RealignmentClustering.runClustering(RealignmentClustering.java:249)
	at au.edu.wehi.socrates.RealignmentClustering.clusterRealignedSC(RealignmentClustering.java:190)
	at au.edu.wehi.socrates.RealignmentClustering.main(RealignmentClustering.java:880)
Used memory is: 4151MB

With 1 thread, 10g memory and on just 1 chromosome. My ulimit is 16382. 
Can I get some help?

**Comment by lparsons** [comment]
Running into this issue as well. Used to get it to work, but now I get this error, same system, even with only 1 thread. Only difference is that there are a few more chromosomes...

**Comment by lparsons** [comment]
The problem seems to be that the `OUTPUT_short_sc.bai` file is opened many times, basically once per `ClusteringWorker` and not closed...

**Comment by karthigayini** [comment]
@lparsons yes, you are right! 
But I don't understand the need to open the file more than 5 million times for just 1 chromosome.

**Comment by lparsons** [comment]
@karthigayini I don't think there is a need, but instead I think this is a bug. Unfortunately, this code hasn't been updated in a year. A bit worried it's unmaintained at the moment. @papenfuss Any comment?

**Comment by karthigayini** [comment]
@papenfuss helped me solve other problems very recently. Hope this is solved too.

**Comment by papenfuss** [comment]
We are fixing any bugs that pop up in Socrates, but our new SV detection tool GRIDSS outperforms Socrates in terms of sensitivity and specificity and will replace Socrates.

**Comment by jibsch** [comment]
There is a new release available that fixes the dangling file handles on my system. 
Please let me know if it works for you as well.

**Comment by lparsons** [comment]
The new release seems to be working for me so far. Thanks @papenfuss and @jibsch !  I'm also trying out GRIDSS, thanks for the heads up (and the excellent software, of course).

**Comment by karthigayini** [comment]
It works for me too. Thanks @jibsch

**Comment by nuin** [comment]
I haven't been using Socrates lately, but as I was the one that created the issue, I will close it as most people are mentioning it is resolved. I will check GRIDSS. Thanks
