### ISSUE TITLE
Missing index file

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/socrates#4]
Socrates appears to not be creating a required index file correctly. A 0 byte input_short_sc.bai file was created.

```
Running Socrates with the following options:
     threads: 9
     long-sc-len: 25
     minimum base quality: 5
     minimum mapping quality: 5
     minimum consensus identity: 95
     support cutoff: 30
     maximum promiscuity: 5
     flanking distance: 50
     keeping duplicates: false
     no short sc cluster pairs: false
     ideal cluster pairs only: false


Stratify BAM file /wehisan/bioinf/bioinf-data/Papenfuss_lab/projects/sv_benchmark/scripts/../data.HG002/c79c7313f835a96e27cc0fc98bbde1d7/input.bam

Realignment of long soft-clips: Running Bowtie2.
Piping Bowtie2 output into RealignmentBAM...
24086124 reads; of these:
  24086124 (100.00%) were unpaired; of these:
    14578229 (60.53%) aligned 0 times
    2150939 (8.93%) aligned exactly 1 time
    7356956 (30.54%) aligned >1 times
39.47% overall alignment rate

Clustering re-alignments. Procducing output in results_Socrates_[paired/unpaired]...
BAM index file does not exist for input_short_sc.bam.
Socrates is creating one for you.
WARNING 2016-12-16 16:17:07     BAMIndexer      For indexing, the BAM file is required to be coordinate sorted. Attempting to index "unsorted" BAM file.
Exception in thread "main" htsjdk.samtools.SAMException: Exception creating BAM index for record D00360:97:H2YVMBCXX:2:1107:18923:87587 2/2 44b aligned read.
     at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:110)
     at htsjdk.samtools.BAMIndexer.createIndex(BAMIndexer.java:309)
     at htsjdk.samtools.BAMIndexer.createIndex(BAMIndexer.java:289)
     at au.edu.wehi.socrates.RealignmentClustering.findIndexFile(RealignmentClustering.java:131)
     at au.edu.wehi.socrates.RealignmentClustering.<init>(RealignmentClustering.java:96)
     at au.edu.wehi.socrates.SOCRATES.main(SOCRATES.java:258)
Caused by: htsjdk.samtools.SAMException: BAM cannot be indexed without setting a fileSource for record D00360:97:H2YVMBCXX:2:1107:18923:87587 2/2 44b aligned read.
     at htsjdk.samtools.BAMIndexMetaData.recordMetaData(BAMIndexMetaData.java:130)
     at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:200)
     at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:108)
     ... 5 more
```

The offending records looks like the following in input_short_sc.bam

```
D00360:97:H2YVMBCXX:2:1107:18923:87587  163     1  10114        6       42M2S   =       10407   337     TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCTT    DDDDDIIIIIIIIIIIIIHIIIIIHHIHIIIIIIII=<G?HI11    PG:Z:novoalign  AS:i:21 UQ:i:21 NM:i:0  MD:Z:42    PQ:i:22    SM:i:0  AM:i:0
D00360:97:H2YVMBCXX:2:1107:18923:87587  163     1  10114        6       42M2S   =       10407   337     TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCTT    DDDDDIIIIIIIIIIIIIHIIIIIHHIHIIIIIIII=<G?HI11    PG:Z:novoalign  AS:i:21 UQ:i:21 NM:i:0  MD:Z:42    PQ:i:22    SM:i:0  AM:i:0
```

**Comment by d-cameron** [comment]
Input file was sorted but had SO:unsorted in the header

**Comment by jibsch** [comment]
I've added a warning message to be thrown in this instance.
