### ISSUE TITLE
Socrate crashed at RealignmentClustering step

### ISSUE THREAD

**Issue by RxLoutre** [PapenfussLab/socrates#5]
Hello,

I've followed instructions to launch Socrates on my data, however, it crashed at the Clustering steps.

Here are the previous command that I tried : 

```
#BAM Stratifier
java -Xmx70g -cp socrates-1.13.1-jar-with-dependencies.jar au.edu.wehi.socrates.BAMStratifier -t 30 '/media/loutre/SUZUKII/alignement/bowtie2-illumina/polished/quiverEssai1/polished-softCliping-sorted.bam'

#Realignement using bowtie2
bowtie2 -x /media/loutre/SUZUKII/indexes/Drosophila-suzukii-p -q polished-softCliping-sorted_long_sc_l25_q5_m5_i95.fastq -p 32 > remapping-socrates.sam

#Sorting bam file
samtools sort remapping-socrates.bam > remapping-socrates-sorted.bam
```
Here is my last command that did not worked :

`java -Xmx70g -cp socrates-1.13.1-jar-with-dependencies.jar au.edu.wehi.socrates.RealignmentClustering remapping-socrates-sorted.bam stepRealignmentSocrates.bam polished-softCliping-sorted.bam.metrics`

And here is the error I got using it : 
```

Clustering re-alignments.
  search for short soft clip cluster: true
  maximum long re-alignment support for unpaired cluster to search for short soft clip cluster: 30
  ideal evidence only: false
  parallel threads: 1
  minimum mapq of re-alignment: 2
  minimum "long" soft clip length: 25
  minimum percent identity of realignment: 95
  minimum number of clusters in a region to be promiscuous region: 5
  size of region: 50bp
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at au.edu.wehi.socrates.RealignmentClustering.runClustering(RealignmentClustering.java:256)
	at au.edu.wehi.socrates.RealignmentClustering.clusterRealignedSC(RealignmentClustering.java:190)
	at au.edu.wehi.socrates.RealignmentClustering.main(RealignmentClustering.java:884)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at au.edu.wehi.socrates.util.SeekableMemoryStream.read(SeekableMemoryStream.java:75)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at htsjdk.samtools.seekablestream.SeekableBufferedStream.read(SeekableBufferedStream.java:100)
	at htsjdk.samtools.AbstractBAMFileIndex$IndexStreamBuffer.readFully(AbstractBAMFileIndex.java:657)
	at htsjdk.samtools.AbstractBAMFileIndex$IndexStreamBuffer.readBytes(AbstractBAMFileIndex.java:681)
	at htsjdk.samtools.AbstractBAMFileIndex.readBytes(AbstractBAMFileIndex.java:435)
	at htsjdk.samtools.AbstractBAMFileIndex.verifyBAMMagicNumber(AbstractBAMFileIndex.java:401)
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:68)
	at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:42)
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:270)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:748)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:434)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:523)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at au.edu.wehi.socrates.RealignmentClustering$ClusteringWorker.buildCluster(RealignmentClustering.java:448)
	at au.edu.wehi.socrates.RealignmentClustering$ClusteringWorker.call(RealignmentClustering.java:347)
	at au.edu.wehi.socrates.RealignmentClustering$ClusteringWorker.call(RealignmentClustering.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Used memory is: 5465MB
```

Did I made a mistake ? Thanks for your help !

Roxane

**Comment by jibsch** [comment]
Hi Roxane,
The steps look sensible to me. 
Just a quick question: is `stepRealignmentSocrates.bam` the short softclip file produces by the BAMStratifier?
The error occurring seems to involve an empty worker pool. Can you confirm that the (long and short SC) bam files are not empty and that the index of `remapping-socrates-sorted.bam ` contains reference sequences?
Cheers,
Jan

**Comment by RxLoutre** [comment]
Hi, sorry for the late reply.

stepRealignementSocrates.bam is the output of the realignementBam command, sorry I forgot to mention that command. I'm rewritting my whole process again so you can understand better what I did : 
```

#BAM Stratifier
java -Xmx70g -cp socrates-1.13.1-jar-with-dependencies.jar au.edu.wehi.socrates.BAMStratifier -t 30 '/media/loutre/SUZUKII/alignement/bowtie2-illumina/polished/quiverEssai1/polished-softCliping-sorted.bam'

#Realignement using bowtie2
bowtie2 -x /media/loutre/SUZUKII/indexes/Drosophila-suzukii-p -q polished-softCliping-sorted_long_sc_l25_q5_m5_i95.fastq -p 32 > remapping-socrates.sam

#Sorting bam file
samtools sort remapping-socrates.bam > remapping-socrates-sorted.bam

#RealignementBAM
java -Xmx70g -cp socrates-1.13.1-jar-with-dependencies.jar au.edu.wehi.socrates.RealignmentBAM remapping-socrates-sorted.bam stepRealignmentSocrates.bam


#Clustering
java -Xmx70g -cp socrates-1.13.1-jar-with-dependencies.jar au.edu.wehi.socrates.RealignmentClustering remapping-socrates-sorted.bam stepRealignmentSocrates.bam polished-softCliping-sorted.bam.metrics

```
 You are right, remapping-socrates-sorted.bai is indeed empty... Long file is a fasta file and short file is a bam file... Is this normal ? But in any cases, theses 2 files are not empty.

Is quite confusing for me, I guess I missed the point somewhere.

**Comment by RxLoutre** [comment]
Sorry to insist, I really want to run Socrates. But even when I'm checking carefully the steps I followed, I can't figure out what I did wrong.
